spring:
  application:
    name: assignment2

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/assignment_2_db?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: update
